**Introducción a NumPy**

NumPy (Numerical Python) es una biblioteca fundamental para la computación científica en Python.  Proporciona un objeto de matriz multidimensional de alto rendimiento y herramientas para trabajar con estas matrices. NumPy facilita el uso de Python con operaciones matemáticas complejas, proporcionando estructuras de datos y funciones eficientes para trabajar con matrices y arreglos. En esencia, NumPy es la base de casi todo el ecosistema de ciencia de datos en Python.

**Puntos Clave de NumPy**

- **ndarray**: El corazón de NumPy es el objeto `ndarray` (array n-dimensional), una estructura de datos eficiente que permite almacenar y manipular grandes conjuntos de datos numéricos. Los `ndarray` son homogéneos, lo que significa que todos los elementos deben ser del mismo tipo de datos, lo que permite operaciones vectoriales rápidas. Esta característica, junto con los algoritmos optimizados de NumPy, proporciona un rendimiento significativamente mayor en comparación con las listas estándar de Python, especialmente cuando se trabaja con grandes conjuntos de datos.
- **Funcionalidad matemática**: NumPy ofrece una amplia gama de funciones matemáticas para realizar operaciones elemento a elemento en arrays, incluyendo operaciones aritméticas, trigonométricas, lógicas y muchas más. Estas funciones están altamente optimizadas para el rendimiento, lo que hace que NumPy sea mucho más rápido que usar bucles Python estándar para realizar cálculos numéricos.
- **Broadcasting**: NumPy permite realizar operaciones entre arrays de diferentes formas, mediante un mecanismo llamado "broadcasting". Esto simplifica el código y lo hace más legible, al evitar la necesidad de bucles explícitos para alinear las dimensiones de los arrays.
- **Integración con otras bibliotecas**: NumPy se integra perfectamente con otras bibliotecas del ecosistema científico de Python, como SciPy (para computación científica), Pandas (para análisis de datos) y Matplotlib (para visualización). Estas bibliotecas a menudo utilizan NumPy como base para sus estructuras de datos y algoritmos.

**Usos de NumPy**

NumPy se utiliza en una amplia variedad de aplicaciones, incluyendo:

- **Análisis de datos**: NumPy proporciona las herramientas para limpiar, transformar y analizar grandes conjuntos de datos. Sus capacidades de manipulación de arrays son esenciales para tareas como la selección de datos, la agregación y el cálculo de estadísticas descriptivas. Por ejemplo, se puede usar NumPy para calcular la media, la mediana y la desviación estándar de un conjunto de datos, o para filtrar datos basados en ciertos criterios.
- **Aprendizaje automático**: NumPy es la base de muchas bibliotecas de aprendizaje automático, como scikit-learn y TensorFlow. Los arrays de NumPy se utilizan para representar datos de entrenamiento, pesos de modelos y otras estructuras de datos esenciales en algoritmos de aprendizaje automático. Por ejemplo, un conjunto de imágenes para entrenar un modelo de reconocimiento de imágenes se puede representar como un array de NumPy donde cada elemento es una matriz que representa una imagen.
- **Procesamiento de imágenes**: NumPy se utiliza para representar imágenes como arrays multidimensionales, donde cada elemento del array representa un píxel. Esto permite realizar operaciones de procesamiento de imágenes como el filtrado, la segmentación y la extracción de características. Por ejemplo, una imagen en escala de grises se puede representar como un array bidimensional de NumPy, donde cada elemento del array corresponde a un píxel y el valor del elemento representa la intensidad del píxel.
- **Álgebra lineal**: NumPy proporciona potentes herramientas para realizar operaciones de álgebra lineal, como la multiplicación de matrices, el cálculo de determinantes, la resolución de sistemas de ecuaciones lineales y la descomposición de matrices. Estas capacidades son esenciales en una variedad de aplicaciones, como el análisis de datos, el aprendizaje automático y la computación gráfica.
- **Simulación científica**: NumPy se utiliza en simulaciones científicas para modelar fenómenos físicos, como el movimiento de partículas, la dinámica de fluidos y la propagación de ondas. Su capacidad para realizar cálculos numéricos eficientes es crucial para estas aplicaciones. Además, NumPy ofrece un amplio conjunto de funciones para generar números aleatorios con diferentes distribuciones, lo que es fundamental para realizar simulaciones y experimentos numéricos.

**Limitaciones de NumPy**

Aunque NumPy es una herramienta poderosa, tiene algunas limitaciones:

- **No está diseñado para datos simbólicos**: NumPy se centra en la computación numérica y no es adecuado para trabajar con datos simbólicos o expresiones algebraicas. Para este tipo de tareas, se recomienda utilizar bibliotecas como `SymPy`.
- **No es un lenguaje de programación completo**: NumPy es una biblioteca, no un lenguaje de programación completo. No ofrece características como estructuras de control de flujo complejas o la definición de funciones personalizadas. Para estas tareas, se utiliza Python en conjunto con NumPy.
- **Puede ser menos eficiente para datos no numéricos**: Aunque NumPy es altamente eficiente para datos numéricos, puede ser menos eficiente para trabajar con datos no numéricos, como cadenas de texto. En estos casos, otras bibliotecas como Pandas pueden ser más adecuadas.

Ejemplo 1: Creación de Arrays y Operaciones Básicas

In [ ]:
!pip install numpy

In [1]:
import numpy as np

# Crear un array a partir de una lista de Python
a = np.array([1, 2, 3, 4, 5])
print("Array a:", a)

# Crear un array con números en un rango (0 a 9)
b = np.arange(10)
print("Array b (0 a 9):", b)

# Crear un array con números equidistantes entre 0 y 1 (5 valores)
c = np.linspace(0, 1, 5)
print("Array c (linspace):", c)


Array a: [1 2 3 4 5]
Array b (0 a 9): [0 1 2 3 4 5 6 7 8 9]
Array c (linspace): [0.   0.25 0.5  0.75 1.  ]


`np.array` convierte listas en arrays de NumPy.

`np.arange` genera arrays con secuencias de números.

`np.linspace` crea arrays con valores equidistantes.

Ejemplo 2: Indexado y Slicing

In [ ]:
import numpy as np

# Crear un array de 10 elementos (0 a 9)
arr = np.arange(10)
print("Array completo:", arr)

# Extraer elementos desde el índice 2 hasta el 6 (el 7 no se incluye)
sub_arr = arr[2:7]
print("Sub-array (índices 2 a 6):", sub_arr)

# Acceder al primer y último elemento
print("Primer elemento:", arr[0])
print("Último elemento:", arr[-1])

El indexado con corchetes permite seleccionar elementos.

Los índices negativos acceden a elementos desde el final.

Ejemplo 3: Operaciones Aritméticas Vectorizadas

In [4]:
import numpy as np

# Definir dos arrays de igual tamaño
x = np.array([1, 2, 3, 4, 5])
y = np.array([10, 20, 30, 40, 50])

# Suma y multiplicación elemento a elemento
suma = x + y
producto = x * y

print("Suma:", suma)
print("Producto:", producto)

Suma: [11 22 33 44 55]
Producto: [ 10  40  90 160 250]


Las operaciones se aplican de forma vectorizada, es decir, se realizan elemento a elemento sin necesidad de bucles.

Ejemplo 4: Broadcasting

In [5]:
import numpy as np

# Crear un array 2D (matriz)
A = np.array([[1, 2, 3],
              [4, 5, 6]])
              
# Crear un array 1D
b = np.array([10, 20, 30])

# Sumar b a cada fila de A (b se "difunde" para adaptarse a la forma de A)
resultado = A + b
print("Resultado del broadcasting:\n", resultado)

Resultado del broadcasting:
 [[11 22 33]
 [14 25 36]]


Broadcasting permite realizar operaciones entre arrays de diferentes dimensiones siempre que sean compatibles.

Ejemplo 5: Operaciones con Matrices

In [ ]:
import numpy as np

# Definir dos matrices
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# Multiplicación de matrices
producto = np.dot(A, B)  # o también A @ B
print("Producto de matrices:\n", producto)

# Transpuesta de la matriz A
print("Transpuesta de A:\n", A.T)

# Cálculo del determinante de A
determinante = np.linalg.det(A)
print("Determinante de A:", determinante)

`np.dot` o el operador`@` se usan para multiplicación matricial.

`A.T` devuelve la transpuesta de la matriz.

`np.linalg.det` calcula el determinante.

Ejemplo 6: Estadísticas y Manipulación de Datos

In [6]:
import numpy as np

# Generar un array con 100 números aleatorios entre 0 y 1
datos = np.random.rand(100)

# Calcular algunas estadísticas
media = np.mean(datos)
mediana = np.median(datos)
desviacion = np.std(datos)

print("Media:", media)
print("Mediana:", mediana)
print("Desviación estándar:", desviacion)

Media: 0.469188480601939
Mediana: 0.4609679860872097
Desviación estándar: 0.28387576249237123


Funciones estadísticas como `np.mean`, `np.median` y `np.std` facilitan el análisis de datos.

**Ejercicio 1: Análisis de una Matriz de Datos**

**Planteamiento:**

Genera una matriz de 5×5 con números aleatorios enteros entre 1 y 50. Realiza las siguientes operaciones:

- Calcula la suma de cada fila y de cada columna.
- Encuentra el valor máximo de cada fila.
- Calcula la suma de la diagonal principal.
- Transpone la matriz y luego multiplica la matriz original por su transpuesta.

**Pistas:**

- Usa `np.random.randint` para generar la matriz.
- Para sumar filas y columnas, utiliza `np.sum` especificando el eje correspondiente.
- La función `np.diag` te ayudará a extraer la diagonal principal.

In [7]:
import numpy as np

def solucion_matriz():
    # Generar matriz 5x5 con números aleatorios entre 1 y 50
    matriz = np.random.randint(1, 51, size=(5, 5))
    print("Matriz original:\n", matriz)

    # Suma de filas y columnas
    suma_filas = np.sum(matriz, axis=1)
    suma_columnas = np.sum(matriz, axis=0)
    print("\nSuma de filas:", suma_filas)
    print("\nSuma de columnas:", suma_columnas)

    # Valor máximo de cada fila
    max_filas = np.max(matriz, axis=1)
    print("\nValor máximo de cada fila:", max_filas)

    # Suma de la diagonal principal
    diagonal = np.diag(matriz)
    suma_diagonal = np.sum(diagonal)
    print("\nDiagonal principal:", diagonal)
    print("\nSuma de la diagonal principal:", suma_diagonal)

    # Transposición y multiplicación
    matriz_transpuesta = matriz.T
    matriz_producto = np.dot(matriz, matriz_transpuesta)
    print("\nMatriz transpuesta:\n", matriz_transpuesta)
    print("\nProducto de la matriz original por su transpuesta:\n", matriz_producto)

In [8]:
solucion_matriz()

Matriz original:
 [[30 35 14 40  9]
 [38 26 20 38 24]
 [ 6 12 17 45 43]
 [37 15 21 29 33]
 [15 42 20 31 27]]

Suma de filas: [128 146 123 135 135]

Suma de columnas: [126 130  92 183 136]

Valor máximo de cada fila: [40 38 45 37 42]

Diagonal principal: [30 26 17 29 27]

Suma de la diagonal principal: 129

Matriz transpuesta:
 [[30 38  6 37 15]
 [35 26 12 15 42]
 [14 20 17 21 20]
 [40 38 45 29 31]
 [ 9 24 43 33 27]]

Producto de la matriz original por su transpuesta:
 [[4002 4066 3025 3386 3683]
 [4066 4540 3622 4110 3888]
 [3025 3622 4343 3483 3490]
 [3386 4110 3483 3965 3395]
 [3683 3888 3490 3395 4079]]


**Ejercicio 2: Estadísticas y Normalización de Datos**

**Planteamiento:**

Genera un array 2D de dimensión 100×4 en el que cada columna representa una variable diferente y cada fila una observación. Los valores deben ser números aleatorios flotantes entre 0 y 100. Realiza las siguientes operaciones:

- Calcula la media, mediana y desviación estándar de cada columna.
- Normaliza cada columna (resta la media y divide por la desviación estándar).
- Encuentra la fila (observación) que tenga el valor máximo en la segunda columna (índice 1).

**Pistas:**

- Usa `np.random.uniform(0, 100, (100, 4))` para generar el array.
- Aplica `np.mean`, `np.median` y `np.std` con el parámetro axis=0 para operar por columnas.
- Para la normalización, puedes utilizar operaciones vectorizadas.

In [13]:
import numpy as np

def generar_matriz_2D():
    # Generar array 2D de 100x4 con números aleatorios entre 0 y 100
    array_2d = np.random.uniform(0, 100, (100, 4))
    print("Array 2D original:\n", array_2d)

    # Estadísticas de cada columna
    media_columnas = np.mean(array_2d, axis=0)
    mediana_columnas = np.median(array_2d, axis=0)
    desviacion_estandar_columnas = np.std(array_2d, axis=0)
    print("\nMedia de cada columna:", media_columnas)
    print("\nMediana de cada columna:", mediana_columnas)
    print("\nDesviación estándar de cada columna:", desviacion_estandar_columnas)

    # Normalizar cada columna
    array_normalizado = (array_2d - media_columnas) / desviacion_estandar_columnas
    print("\nArray 2D normalizado:\n", array_normalizado)

    # Encontrar fila con valor máximo en la segunda columna
    fila_max_segunda_columna = np.argmax(array_2d[:, 1])
    print("\nFila con valor máximo en la segunda columna:", fila_max_segunda_columna)

In [ ]:
generar_matriz_2D()